### ISSUE TITLE
DICA para o repositório

### ISSUE THREAD

**Issue by MigPlayer6032** [renancaldasdev/renancaldasdev.github.io#1]
Dae Renan, tudo certo?
Cara, posso te dar uma dica top? Tente alterar o nome desse repositório para `renancaldasdev.github.io`.
Isso vai fazer com que os seus links possam ser acessados a partir de [https://renancaldasdev.github.io](https://renancaldasdev.github.io/). 
Tirando isso, a página tá top d+, foi muito bem desenvolvido. 
Parabéns!

**Comment by renancaldasdev** [comment]
Opa irmão, obrigado pela dica, alterei aqui e ficou top.
tmj mano
